[FLINK-35420][hadoop-compatibility][test] Workaround some strange scala compilation issue
Without this fix a couple of people did experience compilation error in the IntelliJ:

WordCountMapredITCase.scala:42:8
value isFalse is not a member of ?0
possible cause: maybe a semicolon is missing before `value isFalse'?
      .isFalse()