[FLINK-30155][streaming] Pretty print MutatedConfigurationException
The new message will look like:

org.apache.flink.client.program.MutatedConfigurationException: Not allowed configuration change(s) were detected:
 - Configuration execution.sorted-inputs.enabled:true not allowed.
 - Configuration execution.runtime-mode was changed from STREAMING to BATCH.
 - Configuration execution.checkpointing.interval:500 ms not allowed in the configuration object CheckpointConfig.
 - Configuration execution.checkpointing.mode:EXACTLY_ONCE not allowed in the configuration object CheckpointConfig.
 - Configuration pipeline.max-parallelism:1024 not allowed in the configuration object ExecutionConfig.
 - Configuration parallelism.default:25 not allowed in the configuration object ExecutionConfig.

	at org.apache.flink.client.program.StreamContextEnvironment.checkNotAllowedConfigurations(StreamContextEnvironment.java:235)
	at org.apache.flink.client.program.StreamContextEnvironment.executeAsync(StreamContextEnvironment.java:175)
	at org.apache.flink.client.program.StreamContextEnvironment.execute(StreamContextEnvironment.java:115)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:2049)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:2027)

Instead of:

org.apache.flink.client.program.MutatedConfigurationException: Configuration execution.sorted-inputs.enabled:true not allowed.
Configuration execution.runtime-mode was changed from STREAMING to BATCH.
Configuration execution.checkpointing.interval:500 ms not allowed in the configuration object CheckpointConfig.
Configuration execution.checkpointing.mode:EXACTLY_ONCE not allowed in the configuration object CheckpointConfig.
Configuration pipeline.max-parallelism:1024 not allowed in the configuration object ExecutionConfig.
Configuration parallelism.default:25 not allowed in the configuration object ExecutionConfig.

	at org.apache.flink.client.program.StreamContextEnvironment.checkNotAllowedConfigurations(StreamContextEnvironment.java:235)
	at org.apache.flink.client.program.StreamContextEnvironment.executeAsync(StreamContextEnvironment.java:175)
	at org.apache.flink.client.program.StreamContextEnvironment.execute(StreamContextEnvironment.java:115)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:2049)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:2027)