[FLINK-27999][hive] Fix Hive3 VirtualColumn NoSuchMethodError
VirtualColumn.VIRTUAL_COLUMN_NAMES has a different type in hive2 vs hive3, causing NoSuchFieldErrors since our code is only compiled against hive2