[FLINK-3337] [runtime] mvn test fails on flink-runtime because curator classes not found
Removes curator dependency exclusions from flink-runtime. This resolves
NoClassDefFoundError exceptions when running `mvn test`.

This partialy reverts e31a4d8.

This closes #1596